---
- name: Prepare node01 and deploy microservices
  hosts: node01
  become: true
  vars:
    # На manager
    app_src_dir: /home/vagrant/services
    # Куда копируем на node01
    app_dest_dir: /home/vagrant/services
    compose_file: "{{ app_dest_dir }}/docker-compose.yml"
    docker_gpg_url: "https://download.docker.com/linux/ubuntu/gpg"
    docker_apt_repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

  tasks:
    - name: Docker | Update repositories cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600 

    - name: Docker | Download Docker GPG key
      ansible.builtin.get_url:
        url: "{{ docker_gpg_url }}"
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"

    - name: Docker | Add Docker repository
      ansible.builtin.apt_repository:
        repo: "{{ docker_apt_repo }}"
        state: present # убедиться что репозиторий есть в системе
        filename: docker.list

    - name: Docker | Install Docker packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true

    - name: Docker | enable and start service
      ansible.builtin.service:
        name: docker
        enabled: true
        state: started

    - name: Docker | add vagrant to docker group
      ansible.builtin.user:
        name: vagrant
        groups: docker
        append: true

    - name: App | ensure destination directory exists on node01
      ansible.builtin.file:
        path: "{{ app_dest_dir }}"
        state: directory
        owner: vagrant
        group: vagrant
        mode: "0755"

    - name: App | copy sources & compose from manager to node01
      ansible.builtin.copy:
        src: "{{ app_src_dir }}/"
        dest: "{{ app_dest_dir }}/"
        owner: vagrant
        group: vagrant
        mode: "0644"
        directory_mode: "0755"

    - name: App | pull/build & start with docker compose
      ansible.builtin.command:
        cmd: "docker compose -f {{ compose_file }} up -d --build"
        chdir: "{{ app_dest_dir }}"
      register: compose_up

    - name: Info | show compose stdout
      ansible.builtin.debug:
        var: compose_up.stdout

    - name: Info | show running containers
      ansible.builtin.command: "docker ps --format '{{.Names}}\t{{.Status}}\t{{.Ports}}'"
      changed_when: false
      register: dps

    - name: Info | containers table
      ansible.builtin.debug:
        var: dps.stdout_lines
