---
# tasks file for roles/apache
- name: Apt | Update cache
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Apt | Install apache2
  apt:
    name: apache2
    state: present

- name: Apache | Enable and start
  service:
    name: apache2
    enabled: true
    state: started

