---
- name: Apt | Update cache
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Apt | Install ACL (for become_user file perms)
  apt:
    name: acl
    state: present
    update_cache: true
  become: true

- name: Apt | Install Postgres and deps
  apt:
    name:
      - "postgresql-{{ postgresql_version }}"
      - postgresql-contrib
      - python3-psycopg2
    state: present

- name: Postgres | Ensure service started
  service:
    name: postgresql
    enabled: true
    state: started

- name: Postgres | Listen on all addresses
  lineinfile:
    path: "/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf"
    regexp: '^#?listen_addresses\s*='
    line: "listen_addresses = '*'"
  notify: Restart Postgres
  become: true

- name: Postgres | Allow LAN in pg_hba.conf
  blockinfile:
    path: "/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf"
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR LAN ACCESS"
    block: |
      host    all    all    {{ pg_listen_cidr }}    md5
  notify: Restart Postgres

- name: DB | Ensure database exists (owner = postgres)
  community.postgresql.postgresql_db:
    name: "{{ pg_db }}"
    owner: postgres
    login_unix_socket: /var/run/postgresql
  become: true
  become_user: postgres

- name: DB | Create table if not exists
  community.postgresql.postgresql_query:
    db: "{{ pg_db }}"
    query: |
      CREATE TABLE IF NOT EXISTS public.students(
        id   SERIAL PRIMARY KEY,
        name TEXT UNIQUE
      );
    login_unix_socket: /var/run/postgresql
  become: true
  become_user: postgres

- name: DB | Insert three rows
  community.postgresql.postgresql_query:
    db: "{{ pg_db }}"
    query: |
      INSERT INTO public.students(name) VALUES
        ('Ramonagr'),
        ('Sandiani'),
        ('Nutmegha')
      ON CONFLICT (name) DO NOTHING;
    login_unix_socket: /var/run/postgresql
  become: true
  become_user: postgres

- name: Postgres | Final restart
  service:
    name: postgresql
    state: restarted

